
/**
 * ***** DO NOT EDIT THIS FILE MANUALLY *****
 * This file is generated automatically by the Reaction
 * plugin loader and will be reset at each startup.
 */

import '/imports/plugins/core/accounts/client';
import '/imports/plugins/core/ui-navbar/client';
import '/imports/plugins/custom/somnium-master/client';
import '/imports/plugins/custom/somnium-theme/client';
