
/**
 * ***** DO NOT EDIT THIS FILE MANUALLY *****
 * This file is generated automatically by the Reaction
 * plugin loader and will be reset at each startup.
 */

import '/imports/plugins/custom/somnium-master/server';
import '/imports/plugins/core/layout/register.js';
import '/imports/plugins/core/ui-navbar/register.js';
import '/imports/plugins/custom/somnium-master/register.js';
